spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          ## 可以直接使用应用名称调用服务
          enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: api-server
          uri: lb://api-server
          predicates:
            - Path=/api/**
          filters:
            ## 截取掉predicates配置的Path的第一段
            - StripPrefix=1
          metadata:
            #### 服务超时设置
            ## 响应超时
            response-timeout: 60000
            ## 连接超时
            connect-timeout: 60000
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: baidu-api
          uri: lb://baidu-api
          predicates:
            - Path=/public/**
          filters:
            - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: debug
