server:
  port: 10020
eureka:
  client:
    service-url:
      defaultZone: http://172.16.78.114:8761/eureka/
  instance:
    ip-address: 172.16.78.116
    hostname: 172.16.78.116
    instance-id: ${eureka.instance.hostname}:${server.port}
## 开启swagger
shunba:
  swagger: true
spring:
  profiles:
    active: dev
  application:
    name: auth-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://172.16.78.114:3306/sc_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
      username: root
      password: 123456
      # 从库数据源
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      statViewServlet:
        enabled: true
        url-pattern: /monitor/druid/*
      filter:
        config:
          enabled: true
        stat:
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: 172.16.78.114
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: -1
        max-idle: 20
        maxTotal: 10000
