server:
  port: 8761
spring:
  application:
    name: eureka
  security:
    user:
      name: test
      password: 123456
      roles: USER
eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #服务端不进行注册
    register-with-eureka: false
    fetch-registry: false
  server:
    #禁用自检，仅建议开发环境使用
    enable-self-preservation: false
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}
    hostname: 127.0.0.1
    prefer-ip-address: true
