server:
  port: 12115
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    ip-address: 172.16.78.114
    hostname: 172.16.78.114
    instance-id: 172.16.78.114:${server.port}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      max-lifetime: 120000
    url: jdbc:mysql://127.0.0.1:3306/shunba?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
## 开启swagger
shunba:
  ## 开启swagger
  swagger: true
  ## 文件上传路径. 结尾别加/
  uploadFolder: '/data/upload'
  ## 司机打卡上报接口地址
  driverClock: 'http://release.api.shunbus.com/baidu'
  ticketFetch: 'http://release.api.shunbus.com/baidu'
  ticketPush: 'http://release.api.shunbus.com/baidu'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
